teaching:
  - role: "Teaching Assistant"
    courses:
      - name: "COMPSCI 682 Neural Networks: A Modern Introduction"
        term: "Fall 2026"

reviewing:
  - type: "Program Committee"
    venues:
      - "New England Computer Vision (NECV) Workshop 2025"
  - type: "Journal Reviewer"
    venues:
      - "International Journal of Computer Vision (IJCV)"
      - "Transactions on Machine Learning Research (TMLR)"
